name: Go
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20", "1.21"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Generate file
        run: make generate
            
      - name: Build
        run: go build -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Lint
        run: make lint

  generate:
    name: Regenerate files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Regenerate files
        run: make generate

      - name: Check for a diff
        run: git diff --exit-code
